└──Funcs
    ├──FuncDecl
    │   ├──ID: func
    │   ├──Type: void
    │   ├──Formals
    │   └──Statements
    │       └──While
    │           ├──RelOp: <
    │           │   ├──Num: 1
    │           │   └──Num: 2
    │           └──Statements
    │               ├──VarDecl
    │               │   ├──ID: x
    │               │   ├──Type: int
    │               │   └──Num: 12
    │               ├──If
    │               │   ├──RelOp: >
    │               │   │   ├──ID: x
    │               │   │   └──Num: 12
    │               │   └──Break
    │               ├──VarDecl
    │               │   ├──ID: y
    │               │   ├──Type: int
    │               │   └──Num: 7
    │               ├──If
    │               │   ├──RelOp: >
    │               │   │   ├──ID: y
    │               │   │   └──Num: 7
    │               │   └──Continue
    │               ├──While
    │               │   ├──RelOp: <
    │               │   │   ├──ID: y
    │               │   │   └──Num: 7
    │               │   └──Statements
    │               │       └──Break
    │               └──Break
    └──FuncDecl
        ├──ID: func
        ├──Type: void
        ├──Formals
        └──Statements
            ├──While
            │   ├──RelOp: <
            │   │   ├──Num: 1
            │   │   └──Num: 2
            │   └──Statements
            │       ├──VarDecl
            │       │   ├──ID: x
            │       │   ├──Type: int
            │       │   └──Num: 12
            │       ├──If
            │       │   ├──RelOp: >
            │       │   │   ├──ID: x
            │       │   │   └──Num: 12
            │       │   └──Break
            │       ├──VarDecl
            │       │   ├──ID: y
            │       │   ├──Type: int
            │       │   └──Num: 7
            │       ├──If
            │       │   ├──RelOp: >
            │       │   │   ├──ID: y
            │       │   │   └──Num: 7
            │       │   └──Continue
            │       └──While
            │           ├──RelOp: <
            │           │   ├──ID: y
            │           │   └──Num: 7
            │           └──Statements
            │               └──Break
            └──Break
